<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Catalog_And_Order_Sys</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\admin\" />
  </ItemGroup>

</Project>
